[package]
name = "sales"
version = "0.1.0"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.0"
regex = "1.11.1"
serde = { version = "1.0.208", features = ["derive"] }
serde_with = "3.9.0"
